//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinHAB.Desktop.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinHAB.Desktop.Localizations.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Server.
        /// </summary>
        public static string ChangeServer {
            get {
                return ResourceManager.GetString("ChangeServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Sitemap.
        /// </summary>
        public static string ChangeSitemap {
            get {
                return ResourceManager.GetString("ChangeSitemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files.
        /// </summary>
        public static string ImageFiles {
            get {
                return ResourceManager.GetString("ImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string InterfaceLanguage {
            get {
                return ResourceManager.GetString("InterfaceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sitemap.
        /// </summary>
        public static string LaunchViewSelectSitemap {
            get {
                return ResourceManager.GetString("LaunchViewSelectSitemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to load.
        /// </summary>
        public static string LaunchViewSelectSitemapToLoad {
            get {
                return ResourceManager.GetString("LaunchViewSelectSitemapToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage link missing in the selected Sitemap..
        /// </summary>
        public static string LaunchViewSelesiteMapHomepageLinkExcepton {
            get {
                return ResourceManager.GetString("LaunchViewSelesiteMapHomepageLinkExcepton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Sitemap.
        /// </summary>
        public static string LaunchViewSelesiteMapHomepageLinkExceptonTitle {
            get {
                return ResourceManager.GetString("LaunchViewSelesiteMapHomepageLinkExceptonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your OpenHAB Server Url.
        /// </summary>
        public static string LaunchViewServerUrlTitle {
            get {
                return ResourceManager.GetString("LaunchViewServerUrlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (e.g. http://localhost:8080/).
        /// </summary>
        public static string LaunchViewServerUrlTitleExample {
            get {
                return ResourceManager.GetString("LaunchViewServerUrlTitleExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart to apply.
        /// </summary>
        public static string RestartToApply {
            get {
                return ResourceManager.GetString("RestartToApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to apply selected image for the application background.
        ///Details:.
        /// </summary>
        public static string UnableApplySelectedImageToBackground {
            get {
                return ResourceManager.GetString("UnableApplySelectedImageToBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background image.
        /// </summary>
        public static string UnableApplySelectedImageToBackgroundTitle {
            get {
                return ResourceManager.GetString("UnableApplySelectedImageToBackgroundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Windows desktop client for OpenHAB.
        /// </summary>
        public static string WinHABDescription {
            get {
                return ResourceManager.GetString("WinHABDescription", resourceCulture);
            }
        }
    }
}
