//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinHAB.Desktop.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinHAB.Desktop.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Server.
        /// </summary>
        public static string ButtonChangeServer {
            get {
                return ResourceManager.GetString("ButtonChangeServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Sitemap.
        /// </summary>
        public static string ButtonChangeSitemap {
            get {
                return ResourceManager.GetString("ButtonChangeSitemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string ButtonConnect {
            get {
                return ResourceManager.GetString("ButtonConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ButtonResetBackground {
            get {
                return ResourceManager.GetString("ButtonResetBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart to apply.
        /// </summary>
        public static string ButtonRestartToApply {
            get {
                return ResourceManager.GetString("ButtonRestartToApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose image.
        /// </summary>
        public static string ButtonSelectBackground {
            get {
                return ResourceManager.GetString("ButtonSelectBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View image.
        /// </summary>
        public static string ButtonViewImage {
            get {
                return ResourceManager.GetString("ButtonViewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string LabelAppearance {
            get {
                return ResourceManager.GetString("LabelAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string LabelBackground {
            get {
                return ResourceManager.GetString("LabelBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files.
        /// </summary>
        public static string LabelImageFiles {
            get {
                return ResourceManager.GetString("LabelImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LabelInterfaceLanguage {
            get {
                return ResourceManager.GetString("LabelInterfaceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sitemap.
        /// </summary>
        public static string LabelSelectSitemap {
            get {
                return ResourceManager.GetString("LabelSelectSitemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (e.g. http://localhost:8080/).
        /// </summary>
        public static string LabelServerAddressExample {
            get {
                return ResourceManager.GetString("LabelServerAddressExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string LabelSettings {
            get {
                return ResourceManager.GetString("LabelSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Windows desktop client for OpenHAB.
        /// </summary>
        public static string LabelWinHABDescription {
            get {
                return ResourceManager.GetString("LabelWinHABDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your OpenHAB Server Url.
        /// </summary>
        public static string LabelYourOpenHabServerUrl {
            get {
                return ResourceManager.GetString("LabelYourOpenHabServerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to apply selected image for the application background.
        ///Details:.
        /// </summary>
        public static string MessageExceptionOnApplyImageToBackground {
            get {
                return ResourceManager.GetString("MessageExceptionOnApplyImageToBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background image.
        /// </summary>
        public static string MessageExceptionOnApplyImageToBackgroundTitle {
            get {
                return ResourceManager.GetString("MessageExceptionOnApplyImageToBackgroundTitle", resourceCulture);
            }
        }
    }
}
